-- =====================================================================================
--  EduLink — demo data
-- =====================================================================================
--  Fills the database with realistic demo accounts, vacancies, applications, notifications,
--  saved jobs and interviews, so every screen of the system has something to show.
--
--  BEFORE RUNNING: start the backend once. It creates the tables (Flyway migrations) and already
--  inserts the core demo accounts. This script tops that up with extra data, and restores
--  anything that was deleted.
--
--  HOW TO RUN
--    XAMPP:           http://localhost/phpmyadmin → select edulink_db → SQL tab → paste → Go
--    MySQL Workbench: File → Open SQL Script → this file → ⚡ (Execute all)
--    Command line:    mysql -u root -p --default-character-set=utf8mb4 edulink_db < database/demo_data.sql
--
--  SAFE TO RUN AGAIN: existing rows are skipped (matched by email, student number, job title...),
--  so nothing is duplicated and nobody's changed password is overwritten.
--
--  LOGINS (passwords are stored as BCrypt hashes, never as plain text)
--    Admin      admin@edulink.com         admin123
--    Students   *.student@test.com        password123   (alice, bob, thandi, sipho, lerato, naledi, kagiso)
--    Companies  techcompany@test.com      password123   (verified)
--               datawave@test.com         password123   (verified)
--               cloudnine@test.com        password123   (verified)
--               greenbuild@test.com       password123   (NOT verified — use it to demo admin verification)
-- =====================================================================================

USE edulink_db;
SET NAMES utf8mb4;   -- keeps characters such as "—" intact in every SQL client

-- BCrypt hashes of the demo passwords (generated by the application's own PasswordEncoder)
SET @pw_password123 = '$2a$10$VA0ZeO9cIdc6ucZwrtLTcultUHc6BfZhvkYsubv87L4en47itXD0K';
SET @pw_admin123    = '$2a$10$0B.lxOqgb9Bk3k/8gihczOD0Mo9oQ7qCoyTRvtWM9GTgtUUDmB6he';


-- -------------------------------------------------------------------------------------
-- 1. User accounts (login details). user_type decides which portal the user sees.
-- -------------------------------------------------------------------------------------
INSERT IGNORE INTO users (email, password_hash, user_type, is_active, created_at) VALUES
('admin@edulink.com',       @pw_admin123,    'admin',   TRUE, '2026-01-10 08:00:00'),
('alice.student@test.com',  @pw_password123, 'student', TRUE, '2026-03-02 09:00:00'),
('bob.student@test.com',    @pw_password123, 'student', TRUE, '2026-03-05 10:30:00'),
('thandi.student@test.com', @pw_password123, 'student', TRUE, '2026-04-11 14:15:00'),
('sipho.student@test.com',  @pw_password123, 'student', TRUE, '2026-05-20 08:45:00'),
('lerato.student@test.com', @pw_password123, 'student', TRUE, '2026-06-08 16:20:00'),
('naledi.student@test.com', @pw_password123, 'student', TRUE, '2026-08-19 12:10:00'),
('kagiso.student@test.com', @pw_password123, 'student', TRUE, '2026-09-10 15:40:00'),
('techcompany@test.com',    @pw_password123, 'company', TRUE, '2026-02-15 11:00:00'),
('datawave@test.com',       @pw_password123, 'company', TRUE, '2026-03-18 13:00:00'),
('cloudnine@test.com',      @pw_password123, 'company', TRUE, '2026-07-22 10:00:00'),
('greenbuild@test.com',     @pw_password123, 'company', TRUE, '2026-09-01 09:30:00');


-- -------------------------------------------------------------------------------------
-- 2. Student profiles. Skills are comma-separated and drive the job match percentages.
-- -------------------------------------------------------------------------------------
INSERT IGNORE INTO students (user_id, full_name, student_number, course, institution, graduation_year, skills, job_alerts)
SELECT u.user_id, v.full_name, v.student_number, v.course, v.institution, v.graduation_year, v.skills, TRUE
FROM (
    SELECT 'alice.student@test.com' AS email, 'Alice Mbatha' AS full_name, 'STU001' AS student_number,
           'Computer Science' AS course, 'CPUT' AS institution, 2026 AS graduation_year, 'Java, SQL, Python' AS skills
    UNION ALL SELECT 'bob.student@test.com',    'Bob Ndlovu',     'STU002', 'Information Technology', 'UCT', 2025, 'JavaScript, SQL, React'
    UNION ALL SELECT 'thandi.student@test.com', 'Thandi Zulu',    'STU003', 'Data Science', 'Stellenbosch University', 2026, 'Python, SQL, Machine Learning, Statistics, Excel'
    UNION ALL SELECT 'sipho.student@test.com',  'Sipho Dlamini',  'STU004', 'Software Development', 'CPUT', 2026, 'Java, Spring Boot, SQL, Git, HTML/CSS'
    UNION ALL SELECT 'lerato.student@test.com', 'Lerato Mokoena', 'STU005', 'Network Engineering', 'Wits University', 2027, 'Linux, Networking, AWS, Bash'
    UNION ALL SELECT 'naledi.student@test.com', 'Naledi Sithole', 'STU006', 'Information Systems', 'University of Johannesburg', 2026, 'SQL, Power BI, Excel, Business Analysis'
    UNION ALL SELECT 'kagiso.student@test.com', 'Kagiso Molefe',  'STU007', 'Software Engineering', 'Tshwane University of Technology', 2027, 'Docker, Kubernetes, Linux, Python, Git'
) v
JOIN users u ON u.email = v.email;


-- -------------------------------------------------------------------------------------
-- 3. Company profiles. Only verified companies can post jobs.
-- -------------------------------------------------------------------------------------
INSERT IGNORE INTO companies (user_id, company_name, industry, location, website, is_verified)
SELECT u.user_id, v.company_name, v.industry, v.location, v.website, v.is_verified
FROM (
    SELECT 'techcompany@test.com' AS email, 'TechCorp' AS company_name, 'Software Development' AS industry,
           'Cape Town' AS location, 'https://techcorp.example.com' AS website, TRUE AS is_verified
    UNION ALL SELECT 'datawave@test.com',   'DataWave Analytics',     'Data & AI',          'Johannesburg', 'https://datawave.example.com',  TRUE
    UNION ALL SELECT 'cloudnine@test.com',  'CloudNine Solutions',    'Cloud Computing',    'Pretoria',     'https://cloudnine.example.com', TRUE
    UNION ALL SELECT 'greenbuild@test.com', 'GreenBuild Engineering', 'Civil Engineering',  'Durban',       'https://greenbuild.example.com', FALSE
) v
JOIN users u ON u.email = v.email;


-- -------------------------------------------------------------------------------------
-- 4. Job postings. job_type: 'full-time', 'internship' or 'graduate'.
--    CloudNine's deadlines are relative to today, so they always stay open.
-- -------------------------------------------------------------------------------------
INSERT INTO job_postings (company_id, title, description, requirements, location, job_type, application_deadline, is_active, posted_date)
SELECT c.company_id, v.title, v.description, v.requirements, v.location, v.job_type, v.deadline, TRUE, v.posted
FROM (
    SELECT 'techcompany@test.com' AS email, 'Junior Developer' AS title,
           'Join our engineering team to build cloud-based web applications with Java, Spring Boot and modern frontends.' AS description,
           'Java, Spring Boot, SQL, HTML/CSS' AS requirements, 'Cape Town' AS location, 'graduate' AS job_type,
           DATE '2026-12-30' AS deadline, TIMESTAMP '2026-03-10 09:00:00' AS posted
    UNION ALL SELECT 'techcompany@test.com', 'Database Intern',
           'Help optimise database schemas, write stored procedures, and assist with data migrations.',
           'SQL, Database Design, Attention to detail', 'Remote', 'internship', DATE '2026-11-15', TIMESTAMP '2026-03-12 09:00:00'
    UNION ALL SELECT 'techcompany@test.com', 'Frontend Developer (React)',
           'Build accessible, responsive user interfaces for our SaaS products using React and TypeScript.',
           'React, JavaScript, HTML/CSS, Git', 'Cape Town', 'graduate', DATE '2027-01-31', TIMESTAMP '2026-05-02 10:00:00'
    UNION ALL SELECT 'techcompany@test.com', 'QA Engineer',
           'Design and automate test suites for our web platform. Work closely with developers in an agile team.',
           'Testing, Java, Selenium, SQL', 'Cape Town', 'full-time', DATE '2026-12-20', TIMESTAMP '2026-06-15 10:00:00'
    UNION ALL SELECT 'techcompany@test.com', 'Winter Vacation Work',
           'Three-week winter vacation programme for second-year students. (Closed — deadline has passed.)',
           'Java, Teamwork', 'Cape Town', 'internship', DATE '2026-06-30', TIMESTAMP '2026-04-01 08:00:00'
    UNION ALL SELECT 'datawave@test.com', 'Data Analyst Intern',
           'Turn raw business data into dashboards and insights for our retail clients.',
           'Python, SQL, Excel, Power BI', 'Johannesburg', 'internship', DATE '2026-12-15', TIMESTAMP '2026-04-20 09:00:00'
    UNION ALL SELECT 'datawave@test.com', 'Machine Learning Graduate',
           'Join our AI team to build and deploy predictive models. Mentorship programme included.',
           'Python, Machine Learning, Statistics, SQL', 'Remote', 'graduate', DATE '2027-02-28', TIMESTAMP '2026-07-01 09:00:00'
    UNION ALL SELECT 'datawave@test.com', 'Cloud Support Engineer',
           'Support and automate our AWS cloud infrastructure. On-call rotation after onboarding.',
           'Linux, AWS, Networking, Bash', 'Cape Town', 'full-time', DATE '2026-11-30', TIMESTAMP '2026-08-05 09:00:00'
    UNION ALL SELECT 'cloudnine@test.com', 'DevOps Graduate Programme',
           'A 12-month rotation through our platform, SRE and security teams. Build CI/CD pipelines and run containers in production.',
           'Docker, Kubernetes, Linux, Git, Python', 'Pretoria', 'graduate',
           DATE_ADD(CURDATE(), INTERVAL 75 DAY), TIMESTAMP '2026-08-01 09:00:00'
    UNION ALL SELECT 'cloudnine@test.com', 'Business Intelligence Intern',
           'Six-month internship building Power BI reports that help our clients understand their cloud spending.',
           'SQL, Power BI, Excel', 'Hybrid (Pretoria)', 'internship',
           DATE_ADD(CURDATE(), INTERVAL 45 DAY), TIMESTAMP '2026-09-02 09:00:00'
) v
JOIN users u ON u.email = v.email
JOIN companies c ON c.user_id = u.user_id
WHERE NOT EXISTS (SELECT 1 FROM job_postings j WHERE j.company_id = c.company_id AND j.title = v.title);


-- -------------------------------------------------------------------------------------
-- 5. Applications, spread over several months so the admin analytics charts show a trend.
--    status: 'pending', 'reviewed', 'accepted' or 'rejected'. One application per student per job.
-- -------------------------------------------------------------------------------------
INSERT IGNORE INTO applications (job_id, student_id, cover_letter, status, applied_date, status_updated_at)
SELECT j.job_id, s.student_id, v.cover_letter, v.status, v.applied, v.updated
FROM (
    SELECT 'Junior Developer' AS title, 'STU001' AS student_number,
           'I am Alice. I know Java and SQL and would love to join TechCorp!' AS cover_letter,
           'pending' AS status, TIMESTAMP '2026-04-02 10:00:00' AS applied, CAST(NULL AS DATETIME) AS updated
    UNION ALL SELECT 'Database Intern', 'STU002', 'I am Bob, studying at UCT. I want to improve my database skills.',
           'reviewed', TIMESTAMP '2026-04-18 11:00:00', TIMESTAMP '2026-04-25 09:00:00'
    UNION ALL SELECT 'Junior Developer', 'STU004', 'Spring Boot is my favourite framework and I built my final-year project with it.',
           'accepted', TIMESTAMP '2026-05-06 09:30:00', TIMESTAMP '2026-05-20 14:00:00'
    UNION ALL SELECT 'Data Analyst Intern', 'STU003', 'I have built several Power BI dashboards during my Data Science degree.',
           'accepted', TIMESTAMP '2026-05-22 13:00:00', TIMESTAMP '2026-06-03 10:00:00'
    UNION ALL SELECT 'Frontend Developer (React)', 'STU002', 'React is my strongest skill and I would love to grow it at TechCorp.',
           'reviewed', TIMESTAMP '2026-06-10 15:45:00', TIMESTAMP '2026-06-14 09:00:00'
    UNION ALL SELECT 'Database Intern', 'STU001', 'SQL is one of my core skills and I enjoy optimising queries.',
           'rejected', TIMESTAMP '2026-06-21 08:15:00', TIMESTAMP '2026-07-01 12:00:00'
    UNION ALL SELECT 'Machine Learning Graduate', 'STU003', 'My honours project was a machine learning model for crop yield prediction.',
           'pending', TIMESTAMP '2026-07-09 10:20:00', NULL
    UNION ALL SELECT 'QA Engineer', 'STU004', 'I wrote JUnit and Selenium tests for our capstone project.',
           'reviewed', TIMESTAMP '2026-07-28 16:00:00', TIMESTAMP '2026-08-02 09:00:00'
    UNION ALL SELECT 'Cloud Support Engineer', 'STU005', 'I hold an AWS Cloud Practitioner certificate and run my own Linux home lab.',
           'accepted', TIMESTAMP '2026-08-12 09:00:00', TIMESTAMP '2026-08-26 11:00:00'
    UNION ALL SELECT 'Data Analyst Intern', 'STU001', 'Python and SQL are my strengths and I am keen to learn Power BI.',
           'pending', TIMESTAMP '2026-08-30 14:30:00', NULL
    UNION ALL SELECT 'Machine Learning Graduate', 'STU001', 'I completed a machine learning short course and want to specialise in AI.',
           'pending', TIMESTAMP '2026-09-14 10:00:00', NULL
    UNION ALL SELECT 'Frontend Developer (React)', 'STU004', 'I have built responsive UIs with HTML/CSS and am learning React.',
           'pending', TIMESTAMP '2026-09-21 11:10:00', NULL
    UNION ALL SELECT 'Business Intelligence Intern', 'STU006', 'I build Power BI dashboards for my university''s student society and love turning data into decisions.',
           'reviewed', TIMESTAMP '2026-09-08 09:15:00', TIMESTAMP '2026-09-12 10:00:00'
    UNION ALL SELECT 'DevOps Graduate Programme', 'STU007', 'I run a Kubernetes cluster on Raspberry Pis at home and automate everything with Python.',
           'pending', TIMESTAMP '2026-09-18 13:45:00', NULL
    UNION ALL SELECT 'DevOps Graduate Programme', 'STU005', 'Linux and cloud infrastructure are my passion; I am now learning Docker and Kubernetes.',
           'pending', TIMESTAMP '2026-09-24 08:30:00', NULL
) v
JOIN job_postings j ON j.title = v.title
JOIN students s ON s.student_number = v.student_number;


-- -------------------------------------------------------------------------------------
-- 6. Interviews. A company proposes up to three time slots; the student confirms one.
--    Times are relative to today, so they are always in the future.
--    • Bob / Frontend Developer (React):  PROPOSED  — Bob can pick a time when he logs in
--    • Sipho / QA Engineer:               CONFIRMED — shows under "Upcoming interviews"
--    • Naledi / Business Intelligence:    CONFIRMED
-- -------------------------------------------------------------------------------------
INSERT INTO interviews (application_id, mode, location, notes, duration_minutes, status, confirmed_start, created_at)
SELECT a.application_id, v.mode, v.location, v.notes, v.duration, v.status, v.confirmed_start, NOW()
FROM (
    SELECT 'Frontend Developer (React)' AS title, 'STU002' AS student_number, 'ONLINE' AS mode,
           'https://meet.example.com/techcorp-frontend' AS location,
           'A 45-minute conversation with two of our frontend engineers. Please have a project you are proud of ready to show.' AS notes,
           45 AS duration, 'PROPOSED' AS status, CAST(NULL AS DATETIME) AS confirmed_start
    UNION ALL SELECT 'QA Engineer', 'STU004', 'IN_PERSON', 'TechCorp, 12 Bree Street, Cape Town — ask for Thabo at reception',
           'Bring your ID. We will walk through one of your automated test suites.',
           60, 'CONFIRMED', TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 4 DAY), '10:00:00')
    UNION ALL SELECT 'Business Intelligence Intern', 'STU006', 'PHONE', '+27 12 555 0199',
           'A short screening call with our BI lead.',
           30, 'CONFIRMED', TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 6 DAY), '14:30:00')
) v
JOIN job_postings j ON j.title = v.title
JOIN students s ON s.student_number = v.student_number
JOIN applications a ON a.job_id = j.job_id AND a.student_id = s.student_id
WHERE NOT EXISTS (SELECT 1 FROM interviews i WHERE i.application_id = a.application_id);

-- Time slots offered for each interview (only added to interviews that have no slots yet)
INSERT INTO interview_slots (interview_id, starts_at)
SELECT i.interview_id, v.starts_at
FROM (
    SELECT 'Frontend Developer (React)' AS title, 'STU002' AS student_number, TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 3 DAY), '10:00:00') AS starts_at
    UNION ALL SELECT 'Frontend Developer (React)', 'STU002', TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 3 DAY), '14:00:00')
    UNION ALL SELECT 'Frontend Developer (React)', 'STU002', TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 5 DAY), '11:00:00')
    UNION ALL SELECT 'QA Engineer', 'STU004', TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 4 DAY), '10:00:00')
    UNION ALL SELECT 'QA Engineer', 'STU004', TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 5 DAY), '09:00:00')
    UNION ALL SELECT 'Business Intelligence Intern', 'STU006', TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 6 DAY), '14:30:00')
) v
JOIN job_postings j ON j.title = v.title
JOIN students s ON s.student_number = v.student_number
JOIN applications a ON a.job_id = j.job_id AND a.student_id = s.student_id
JOIN interviews i ON i.application_id = a.application_id
WHERE NOT EXISTS (SELECT 1 FROM interview_slots x WHERE x.interview_id = i.interview_id AND x.starts_at = v.starts_at);


-- -------------------------------------------------------------------------------------
-- 7. Saved (bookmarked) jobs
-- -------------------------------------------------------------------------------------
INSERT IGNORE INTO saved_jobs (student_id, job_id, saved_at)
SELECT s.student_id, j.job_id, v.saved_at
FROM (
    SELECT 'STU001' AS student_number, 'Frontend Developer (React)' AS title, TIMESTAMP '2026-09-15 09:00:00' AS saved_at
    UNION ALL SELECT 'STU001', 'QA Engineer',                  TIMESTAMP '2026-09-16 12:30:00'
    UNION ALL SELECT 'STU003', 'Business Intelligence Intern', TIMESTAMP '2026-09-05 08:00:00'
    UNION ALL SELECT 'STU007', 'Cloud Support Engineer',       TIMESTAMP '2026-09-19 17:20:00'
) v
JOIN students s ON s.student_number = v.student_number
JOIN job_postings j ON j.title = v.title;


-- -------------------------------------------------------------------------------------
-- 8. In-app notifications (the bell icon). is_read = FALSE shows as a red badge.
-- -------------------------------------------------------------------------------------
INSERT INTO notifications (user_id, type, message, link, is_read, created_at)
SELECT u.user_id, v.type, v.message, v.link, v.is_read, v.created_at
FROM (
    SELECT 'bob.student@test.com' AS email, 'INTERVIEW_PROPOSED' AS type,
           'TechCorp invited you to an interview for Frontend Developer (React). Choose a time that suits you.' AS message,
           '/student/applications' AS link, FALSE AS is_read, NOW() AS created_at
    UNION ALL SELECT 'sipho.student@test.com', 'APPLICATION_STATUS_CHANGED',
           'Your application for QA Engineer at TechCorp is now under review.', '/student/applications', TRUE, TIMESTAMP '2026-08-02 09:00:00'
    UNION ALL SELECT 'lerato.student@test.com', 'APPLICATION_STATUS_CHANGED',
           'Your application for Cloud Support Engineer at DataWave Analytics is now accepted.', '/student/applications', FALSE, TIMESTAMP '2026-08-26 11:00:00'
    UNION ALL SELECT 'kagiso.student@test.com', 'JOB_MATCH',
           'New job that matches your skills: DevOps Graduate Programme at CloudNine Solutions.', '/jobs', FALSE, TIMESTAMP '2026-09-10 16:00:00'
    UNION ALL SELECT 'naledi.student@test.com', 'JOB_MATCH',
           'New job that matches your skills: Business Intelligence Intern at CloudNine Solutions.', '/jobs', TRUE, TIMESTAMP '2026-09-02 09:05:00'
    UNION ALL SELECT 'techcompany@test.com', 'APPLICATION_RECEIVED',
           'Sipho Dlamini applied for Frontend Developer (React).', '/company/applications', FALSE, TIMESTAMP '2026-09-21 11:10:00'
    UNION ALL SELECT 'cloudnine@test.com', 'APPLICATION_RECEIVED',
           'Lerato Mokoena applied for DevOps Graduate Programme.', '/company/applications', FALSE, TIMESTAMP '2026-09-24 08:30:00'
    UNION ALL SELECT 'cloudnine@test.com', 'COMPANY_VERIFIED',
           'Your company has been verified. You can now post vacancies.', '/company/jobs', TRUE, TIMESTAMP '2026-07-23 09:00:00'
) v
JOIN users u ON u.email = v.email
WHERE NOT EXISTS (SELECT 1 FROM notifications n WHERE n.user_id = u.user_id AND n.message = v.message);


-- -------------------------------------------------------------------------------------
-- Done. Quick check — how many rows each table now has:
-- -------------------------------------------------------------------------------------
SELECT 'users' AS table_name, COUNT(*) AS total_rows FROM users
UNION ALL SELECT 'students',        COUNT(*) FROM students
UNION ALL SELECT 'companies',       COUNT(*) FROM companies
UNION ALL SELECT 'job_postings',    COUNT(*) FROM job_postings
UNION ALL SELECT 'applications',    COUNT(*) FROM applications
UNION ALL SELECT 'interviews',      COUNT(*) FROM interviews
UNION ALL SELECT 'interview_slots', COUNT(*) FROM interview_slots
UNION ALL SELECT 'saved_jobs',      COUNT(*) FROM saved_jobs
UNION ALL SELECT 'notifications',   COUNT(*) FROM notifications;
